select 
	h.home_team as home_team,
	h.away_team as away_team,
	CASE WHEN h.winner = h.home_team THEN 1
	     ELSE 0 END as is_home_win,
		 h.home_score + a.away_score as score_total,
		 h.venue,
	h_l5_goal_assists_avg,
	h_l5_kicks_avg,
	h_l5_handballs_avg,
	h_l5_behinds_avg,
	h_l5_tackles_avg,
	h_l5_hitouts_avg,
	h_l5_inside_50_avg,
	h_l5_clearances_avg,
	h_l5_clangers_avg,
	h_l5_rebound_50_avg,
	h_l5_frees_for_avg,
	h_l5_frees_against_avg,
	h_l5_opp_goal_assists_avg,
	h_l5_opp_kicks_avg,
	h_l5_opp_handballs_avg,
	h_l5_opp_behinds_avg,
	h_l5_opp_tackles_avg,
	h_l5_opp_hitouts_avg,
	h_l5_opp_inside_50_avg,
	h_l5_opp_clearances_avg,
	h_l5_opp_clangers_avg,
	h_l5_opp_rebound_50_avg,
	h_l5_opp_frees_for_avg,
	h_l5_opp_frees_against_avg,
	a_l5_goal_assists_avg,
	a_l5_kicks_avg,
	a_l5_handballs_avg,
	a_l5_behinds_avg,
	a_l5_tackles_avg,
	a_l5_hitouts_avg,
	a_l5_inside_50_avg,
	a_l5_clearances_avg,
	a_l5_clangers_avg,
	a_l5_rebound_50_avg,
	a_l5_frees_for_avg,
	a_l5_frees_against_avg,
	a_l5_opp_goal_assists_avg,
	a_l5_opp_kicks_avg,
	a_l5_opp_handballs_avg,
	a_l5_opp_behinds_avg,
	a_l5_opp_tackles_avg,
	a_l5_opp_hitouts_avg,
	a_l5_opp_inside_50_avg,
	a_l5_opp_clearances_avg,
	a_l5_opp_clangers_avg,
	a_l5_opp_rebound_50_avg,
	a_l5_opp_frees_for_avg,
	a_l5_opp_frees_against_avg
from {{ ref('aux_home_ml_stats_train') }} h
INNER JOIN
	 {{ ref('aux_away_ml_stats_train')}} a 
ON h.match_id = a.match_id
where h_l5_opp_inside_50_avg is NOT NULL and a_l5_opp_inside_50_avg IS NOT NULL